---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Sample Cloudformation template"

Parameters:
  AllowedIP:
    Type: String
    Default: 10.0.0.1/32
    Description: IP Allowed

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a6b2839d44d781b2
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedIP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AllowedIP
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref AllowedIP
      

  
